### PR TITLE
Updates and improvements

### PR DESCRIPTION
**Pull request by lagden**
- change test framework `mocha -> ava` and `istanbul -> nyc`
- prefer async/await
- add xo lint (eslint)
- travis run nodejs 8 LTS

### CODE REVIEW

**Comment by coderhaoxin** [comment]
* eslint: we have https://github.com/koajs/eslint-config-koa
* disable `package-lock`

> change test framework mocha -> ava and istanbul -> nyc

why ?

**Comment by lagden** [comment]
I didn't know about `eslint-config-koa`...
added!

> why?

Mocha requires you to use implicit globals like describe and it with the default interface (which most people use). It's not very opinionated and executes tests serially without process isolation, making it slow.

**Comment by jonathanong** [comment]
generally styling fixes are not accepted. i would take the .travis.yml updates though

**Comment by jonathanong** [comment]
and @coderhaoxin 's suggestions

**Comment by lagden** [comment]
@jonathanong 

the style is according with the `eslint-config-koa`

https://github.com/lagden/conditional-get/blob/3524318c7c854efd479b75bd2fac182c7388029e/package.json#L41

and `mocha -> ava` was "upgrade", but the test content is the same...

Any further suggestions?

**Comment by coderhaoxin** [comment]
https://github.com/koajs/conditional-get/pull/13

**Pull request closed without merging**
